apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-project
  region: us-east-1

managedNodeGroups:
  - name: eks-project
    instanceTypes: ["c3.large", "m3.large", "t3.medium"]
    desiredCapacity: 2 # by default 3 ,if you are not giving
    spot: true
